### ISSUE TITLE
disconnecting exec / data nodes can trigger exec to fire

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#209]
Not sure how to repro or wahts causing this its super weird

**Comment by Brendonovich** [comment]
fixed in aadc35e9ca5f305aa48c6b4f587cee1c7c09cd7b

problem was i was using a signal to store new events + then using an effect to run `emitEvent` whenever the latest event changed, but this was causing all the property accesses within `emitEvent` to become reactive. some would say this is a downside of using solid's reactivity, but honestly it's just bad programming on my part.
we already have a callback for receiving events, i should have just been calling `emitEvent` in there rather than running the events through a signal first.
